version: 2.1

orbs:
  win: circleci/windows@2.4.0

commands:
  choco_install_cmake:
    steps:
      - run:
          name: install cmake
          command: |
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=User'
  checkout_with_git_submodule:
    steps:
      - checkout
      - run:
          name: git submodule
          command: |
            git submodule sync --recursive
            git submodule update --progress --init --recursive

jobs:
  build_test:
    executor: win/default
    steps:
      - checkout_with_git_submodule
      - run:
          name: cmd
          shell: cmd.exe
          command: .cicommon\cmake_vs_build.bat """vs2019"""

workflows:
  version: 2
  build:
    jobs:
      - build_test
